# Applications evaluated
applications:
  - name: "Circlys"
    id: "circlys"
    policy_path: "data/policies/Circlys.docx"
  - name: "Dinar"
    id: "dinar"
    policy_path: "data/policies/Dinar.docx"
  - name: "Safqah"
    id: "safqah"
    policy_path: "data/policies/Safqah.docx"
  - name: "Tarmeez"
    id: "tarmeez"
    policy_path: "data/policies/Tarmeez.docx"
  - name: "Tamra Capital"
    id: "tamra_capital"
    policy_path: "data/policies/Tamra Capital.docx"
  - name: "Malaa"
    id: "malaa"
    policy_path: "data/policies/Malaa.docx"
  - name: "Aseel Invest"
    id: "aseel_invest"
    policy_path: "data/policies/Aseel Invest.docx"
  - name: "Sahm"
    id: "sahm"
    policy_path: "data/policies/Sahm.docx"
  - name: "Hakbah"
    id: "hakbah"
    policy_path: "data/policies/Hakbah.docx"
  - name: "Dawul"
    id: "dawul"
    policy_path: "data/policies/Dawul.docx"
  - name: "Sukuk"
    id: "sukuk"
    policy_path: "data/policies/Sukuk.docx"
  - name: "Awaed"
    id: "awaed"
    policy_path: "data/policies/Awaed.docx"
  - name: "Abyan"
    id: "abyan"
    policy_path: "data/policies/Abyan.docx"
  - name: "Manafa"
    id: "manafa"
    policy_path: "data/policies/Manafa.docx"
  - name: "Rakeez"
    id: "rakeez"
    policy_path: "data/policies/Rakeez.docx"
  - name: "Emakn Alarabiya"
    id: "emakn_alarabiya"
    policy_path: "data/policies/Emakn Alarabiya.docx"
  - name: "Money Loop"
    id: "money_loop"
    policy_path: "data/policies/Money Loop.docx"
  - name: "Ta3meed"
    id: "ta3meed"
    policy_path: "data/policies/Ta3meed.docx"
  - name: "Sulfah"
    id: "sulfah"
    policy_path: "data/policies/Sulfah.docx"
